### ISSUE TITLE
Multipart PKG files are improperly signed / built

### ISSUE THREAD

**Issue by nealosis** [PS3Xploit/PS3xploit-resigner#12] opened 2018-03-28 13:50 UTC
See reference snapshot of issue:
https://imgur.com/a/BRksh

Beyond: Two souls is a 7 part PKG file. When attempting to sign the first part, the resigner tool creates a file that is 32GB, rather than 4GB as it should be. Signing parts 2-6 work as expected but the pkg cannot be installed on PS3 due to part 1 being 32GB.

**Comment by PS3Xploit** [comment] 2018-03-28 20:28
Hi!
It seems that is because the tool only accepts proper pkgs
Your splits are actually invalid pkgs unless you combine
Other way proper splits would have been that has one file on one part and another file on the next but in your case your pkg are cut with a tool similar to ps3 splitter which does this

**Comment by PS3Xploit** [comment] 2018-03-28 20:30
If you believe the issue is occurring with a valid type pkg please open the pkg in HxD and send me a screenshot from the start

**Comment by nealosis** [comment] 2018-03-28 22:23
The files are directly from the PSN
http://psndl.net/view-package/431

Every other pkg I have tested works perfectly, except the games that are split into multiple parts such as Beyond: Two Souls

Is there a tool I need to use to join them into a single pkg?

**Comment by PS3Xploit** [comment] 2018-03-29 00:18
hi, you can try ps3merge. i checked the pkg, the pkg is splitted in a way that it must be combined all together to actually be a valid pkg in itself

**Comment by DarkGreyCat** [comment] 2018-04-01 05:51
I have the same problem and ps3merge doesn't recognise these packages as split, I'm guessing because they're not split by a tool but by PSN.

**Comment by PS3Xploit** [comment] 2018-04-01 11:06
They are splitted by some tool, I verified the pkg
Anyways, I got no idea which tool. If you add extension to each pkg, they might get merged by ps3merge otherwise idk

**Comment by nealosis** [comment] 2018-04-01 11:52
>  If you add extension to each pkg, they might get merged by ps3merge
I've tried everything I can think of in ps3merge and I've given up. That tool can't work with files split by Sony PSN. 

Long story short, using PS3Xploit V3 you are locked out of any game that is splitted on PSN (other than Ni No Kuni; for some reason the parts of that game are standalone and don't have this issue)

**Comment by DarkGreyCat** [comment] 2018-04-01 12:08
It worked for me, I mean it sucessfully merged the parts into a single pkg, but I'm not sure if it's usable as I'm still resigning it.

How to do it:
Beyond Two Souls (16).pkg
Beyond Two Souls (26).pkg
Beyond Two Souls (36).pkg
etc.
Rename to: (Notice the missing numbers)
Beyond Two Souls.pkg.66600
Beyond Two Souls.pkg.66601
Beyond Two Souls.pkg.66602
etc.

PS3Merge sucesfully merged the 7 parts into a single pkg file with the same size as them. Again I'm still resigning that pkg file so I can't yet confirm if it works.

**Comment by nealosis** [comment] 2018-04-01 12:12
> It worked for me, I mean it sucessfully merged the parts into a single pkg

Excellent. I did not try the 666* extensions. I'll give that a shot! Thanks kindly

**Closed** 2018-04-03 09:10 UTC

**Comment by nealosis** [comment] 2018-04-03 12:05
Why is this ticket closed? Did we get verification from anyone that the join + install works because the installation failed for me after joining.

**Comment by DarkGreyCat** [comment] 2018-04-03 22:05
Yup it worked perfectly for me. Both for Yakuza 5 and Beyond Two Souls. Just in case it makes any difference, I merged the pkg's without resigning, and after that I resigned the single large pkg and installed.
